import 'package:flutter/material.dart';
import 'package:up_todo/Feature/Category/data/models/category_model.dart';

List<CategoryModel> generateCategories() {
  return [
    CategoryModel(
      id: 1,
      name: 'Grocery',
      colorBg: const Color(0xffCCFF80).value,
      iconCodePoint: Icons.breakfast_dining_outlined.codePoint,
      iconFontFamily: Icons.breakfast_dining_outlined.fontFamily!,
      iconFontPackage: Icons.breakfast_dining_outlined.fontPackage,
      colorValueIcon: const Color(0xff21A300).value,
    ),
    CategoryModel(
      id: 2,
      name: 'Work',
      colorBg: const Color(0xffFF9680).value,
      iconCodePoint: Icons.work_outline.codePoint,
      colorValueIcon: const Color(0xFFA31D00).value,
      iconFontFamily: Icons.work_outline.fontFamily!,
      iconFontPackage: Icons.work_outline.fontPackage,
    ),
    CategoryModel(
      id: 3,
      name: 'Sports',
      colorBg: const Color(0xff80FFFF).value,
      iconCodePoint: Icons.sports_tennis_sharp.codePoint,
      colorValueIcon: const Color(0xff3B734B).value,
      iconFontFamily: Icons.sports_tennis_sharp.fontFamily!,
      iconFontPackage: Icons.sports_tennis_sharp.fontPackage,
    ),
    CategoryModel(
      id: 4,
      name: 'Design',
      colorBg: const Color(0xff80FFD9).value,
      iconCodePoint: Icons.trip_origin_sharp.codePoint,
      colorValueIcon: const Color(0xff00A372).value,
      iconFontFamily: Icons.trip_origin_sharp.fontFamily!,
      iconFontPackage: Icons.trip_origin_sharp.fontPackage,
    ),
    CategoryModel(
      id: 5,
      name: 'University',
      colorBg: const Color(0xff809CFF).value,
      iconCodePoint: Icons.school.codePoint,
      colorValueIcon: const Color(0xff0055A3).value,
      iconFontFamily: Icons.school.fontFamily!,
      iconFontPackage: Icons.school.fontPackage,
    ),
    CategoryModel(
      id: 6,
      name: 'Social',
      colorBg: const Color(0xffFF80EB).value,
      iconCodePoint: Icons.mic_none_outlined.codePoint,
      colorValueIcon: const Color(0xffA30089).value,
      iconFontFamily: Icons.mic_none_outlined.fontFamily!,
      iconFontPackage: Icons.mic_none_outlined.fontPackage,
    ),
    CategoryModel(
      id: 7,
      name: 'Music',
      colorBg: const Color(0xffFC80FF).value,
      iconCodePoint: Icons.music_note_outlined.codePoint,
      colorValueIcon: const Color(0xffA000A3).value,
      iconFontFamily: Icons.music_note_outlined.fontFamily!,
      iconFontPackage: Icons.music_note_outlined.fontPackage,
    ),
    CategoryModel(
      id: 8,
      name: 'Health',
      colorBg: const Color(0xff80FFA3).value,
      iconCodePoint: Icons.monitor_heart_outlined.codePoint,
      colorValueIcon: const Color(0xff00A3A3).value,
      iconFontFamily: Icons.monitor_heart_outlined.fontFamily!,
      iconFontPackage: Icons.monitor_heart_outlined.fontPackage,
    ),
    CategoryModel(
      id: 9,
      name: 'Movie',
      colorBg: const Color(0xff80D1FF).value,
      iconCodePoint: Icons.video_camera_back_outlined.codePoint,
      colorValueIcon: const Color(0xff0069A3).value,
      iconFontFamily: Icons.video_camera_back_outlined.fontFamily!,
      iconFontPackage: Icons.video_camera_back_outlined.fontPackage,
    ),
    CategoryModel(
      id: 10,
      name: 'Home',
      colorBg: const Color(0xffFF8080).value,
      iconCodePoint: Icons.home_outlined.codePoint,
      colorValueIcon: const Color(0xffA30000).value,
      iconFontFamily: Icons.home_outlined.fontFamily!,
      iconFontPackage: Icons.home_outlined.fontPackage,
    ),
  ];
}
